<a href="https://colab.research.google.com/github/avinseth/Prompt-Engineering-Techniques/blob/Coding-Hub/Demo_00_Text_To_Vector_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Text Processing and Feature Extraction in NLP**

### **Objective:**  
To understand and implement key text preprocessing and feature extraction techniques in Natural Language Processing (NLP), including tokenization, Bag of Words (BoW) vectorization, one-hot encoding, and word embeddings (Word2Vec).

---

### **Note:**  
- Before running any demo, ensure that the **requirements.txt** file is installed. This file contains all the required dependencies for **all demos and guided practices under Building LLM Applications**.
- If the dependencies were already installed earlier (after creating the virtual environment), there is no need to install them again. You can directly proceed with running the demo.
- Refer to Lesson_01 **Demo_01_Zero_Shot_Prompting.ipynb** Step 1 for creating a virtual environment and installing the requirements.txt
- Ensure you select the right kernel **Python (myenv)** while running the demos
---


### **Steps to perform:**
1. Tokenization  
2. Bag of Words (BoW) Vectorization  
3. One-Hot Encoding  
4. Word Embeddings (Word2Vec)  

---


### __Step 1: Tokenization__


- **What is Tokenization?**  
  Tokenization is the process of breaking text into smaller units called *tokens*, such as words or subwords.  
  This helps in text analysis, NLP preprocessing, and model training.  


In [ ]:
text_data = [
    "AI is transforming the world.",
    "Natural language processing is a subset of AI.",
    "Deep learning and machine learning are popular AI techniques.",
    "AI applications are diverse and growing rapidly."
]


In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')


# Tokenize the text data
from nltk.tokenize import word_tokenize

tokenized_data = [word_tokenize(sentence) for sentence in text_data]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
tokenized_data

[['AI', 'is', 'transforming', 'the', 'world', '.'],
 ['Natural', 'language', 'processing', 'is', 'a', 'subset', 'of', 'AI', '.'],
 ['Deep',
  'learning',
  'and',
  'machine',
  'learning',
  'are',
  'popular',
  'AI',
  'techniques',
  '.'],
 ['AI', 'applications', 'are', 'diverse', 'and', 'growing', 'rapidly', '.']]

- Each sentence is split into individual words, preparing the data for further processing.

## __Step 2: Bag of Words (BoW) Vectorization__

- What is Bag of Words? \
    Bag of Words (BoW) converts text into numerical form by counting the occurrence of each word across the dataset.
    It ignores grammar and word order, focusing purely on word frequency.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the text data
vectorized_data = vectorizer.fit_transform(text_data)

# Get the feature names (tokens)
feature_names = vectorizer.get_feature_names_out()

# Convert to array for better visualization
vector_array = vectorized_data.toarray()

feature_names, vector_array


(array(['ai', 'and', 'applications', 'are', 'deep', 'diverse', 'growing',
        'is', 'language', 'learning', 'machine', 'natural', 'of',
        'popular', 'processing', 'rapidly', 'subset', 'techniques', 'the',
        'transforming', 'world'], dtype=object),
 array([[1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0],
        [1, 1, 0, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
        [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]]))

- Each row in the matrix represents a sentence, and each column represents a unique word in the corpus.

## __Step 3: One-Hot Encoding__

- What is One-Hot Encoding? \
    One-Hot Encoding represents each unique word as a binary vector.
    Each word gets a unique index, and a value of 1 indicates the presence of that word in a given sentence.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample Text Dataset
text_data = [
    "AI is transforming the world.",
    "Natural language processing is a subset of AI.",
    "Deep learning and machine learning are popular AI techniques.",
    "AI applications are diverse and growing rapidly."
]

# Tokenize
tokenized_data = [word_tokenize(sentence.lower()) for sentence in text_data]

# Flatten tokens
flattened_tokens = [word for sentence in tokenized_data for word in sentence]

# Vocabulary
vocabulary = sorted(list(set(flattened_tokens)))

# OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(np.array(vocabulary).reshape(-1, 1))

# TRUE one-hot encoding (per word)
true_one_hot = {
    word: encoder.transform([[word]])[0]
    for word in vocabulary
}

# Example: one-hot for "ai"
true_one_hot['natural']


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

## __Step 4: Word Embeddings (Word2Vec)__

- What is Word2Vec? \
    Word2Vec converts words into dense vector representations where words with similar meanings are positioned closer in the vector space.
    This helps models understand contextual relationships between words.

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 48.6 MB/s eta 0:00:00


In [ ]:
import nltk
from gensim.models import Word2Vec

nltk.download('punkt')

# Sample Text Dataset
text_data = [
    "AI is transforming the world.",
    "Natural language processing is a subset of AI.",
    "Deep learning and machine learning are popular AI techniques.",
    "AI applications are diverse and growing rapidly."
]

# Tokenize the text data
tokenized_data = [word_tokenize(sentence.lower()) for sentence in text_data]

# Train the Word2Vec model
model = Word2Vec(sentences=tokenized_data, vector_size=100, window=5, min_count=1, workers=4)

# Get the vocabulary
vocabulary = list(model.wv.index_to_key)

# Get word embeddings for the vocabulary
word_embeddings = {word: model.wv[word] for word in vocabulary}

# Example: Get embedding for the word 'ai'
embedding_ai = word_embeddings['ai']

vocabulary, embedding_ai


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


(['.',
  'ai',
  'are',
  'and',
  'learning',
  'is',
  'rapidly',
  'growing',
  'diverse',
  'applications',
  'techniques',
  'popular',
  'machine',
  'deep',
  'of',
  'subset',
  'a',
  'processing',
  'language',
  'natural',
  'world',
  'the',
  'transforming'],
 array([-8.6193858e-03,  3.6666067e-03,  5.1906640e-03,  5.7419776e-03,
         7.4684573e-03, -6.1679599e-03,  1.1067535e-03,  6.0518878e-03,
        -2.8410414e-03, -6.1753602e-03, -4.1022227e-04, -8.3720284e-03,
        -5.6005944e-03,  7.1055479e-03,  3.3529128e-03,  7.2231502e-03,
         6.8031158e-03,  7.5339889e-03, -3.7909565e-03, -5.6589517e-04,
         2.3494184e-03, -4.5187226e-03,  8.3891312e-03, -9.8588532e-03,
         6.7676185e-03,  2.9139910e-03, -4.9333661e-03,  4.4013290e-03,
        -1.7421308e-03,  6.7122704e-03,  9.9633439e-03, -4.3641757e-03,
        -5.9878774e-04, -5.6986115e-03,  3.8479066e-03,  2.7841718e-03,
         6.8920157e-03,  6.1013806e-03,  9.5399832e-03,  9.2724329e-03,
       

- Word embeddings capture semantic meaning — for example, words like AI, machine, and learning will have similar vector representations.

### __Conclusion:__

By following these steps, you have implemented fundamental text preprocessing and feature extraction techniques in NLP, including tokenization, Bag of Words, one-hot encoding, and Word2Vec embeddings. These methods form the foundation of modern NLP workflows, helping machines interpret and process human language effectively.

---